project:
  type: manuscript

manuscript:
  article: index.qmd

format:
  html: default
#    comments:
#      hypothesis: true
  docx: default
  jats: default

  # (other formats)
  # pdf: default
  typst: 
    template: "template.typ"
    template-partials:
      - "definitions.typ"
      - "typst-template.typ"
      - "typst-show.typ"
      - "biblio.typ"
      - "notes.typ"
    header-includes: |
      #set bibliography(title: "___")
      #set table(
        stroke: (
          x: .1pt,
          y: .1pt
        ),
        fill: (x, y) => if y == 0 { rgb(245, 245, 245) }
      )
      #show table: it => {
        set text(size: 7pt)
        set par (
          justify: false
        )
        it
      }
      #show heading: it => [
        #it
        #v(0.6em)
      ]
      #show figure.caption: set align(left)
      #show footnote.entry: it => {
        set par(first-line-indent: 0em)
        [#h(-1em)#it]  // Pulls the number back
      }
    fontsize: 10pt
    papersize: a4
    toc: true
    section-numbering: 1.1.a
    columns: 1
    keep-typ: true
    margin:
      top: 2cm
      bottom: 2cm
      left: 2cm 
      right: 2cm

execute:
  freeze: auto

editor: visual

